#----------Preliminaries----------#
rm(list = ls())
section <- "Data"
subsection <- "robustness_check"
title <- "mother"

HPC <- TRUE # Set False if you wish to run locally and test the baseline results

# Specify the root directory:
if(HPC){
  dir_root <- "/home/weiqiw/synthetic_dynasty_analysis"
}else{
  dir_root <- "~/Desktop/synthetic_dynasty_analysis"
}

setwd(dir_root) # Set working directory
# Define subdirectories for logs and figures:
dir_log <- paste0(dir_root, "/code/", "_LOGS","/", section)
log_path <- paste0(dir_log, "/", subsection, "_", title, "_log.txt")
dir_data <- paste0(dir_root, "/" ,section, "/", subsection)
# Ensure all necessary directories exist under your root folder
# if not, the function will create folders for you

create_dir_if_missing <- function(dir) {
  if (!dir.exists(dir)) {
    dir.create(dir, recursive = TRUE)
    message("Created directory: ", dir)
  } else {
    message("Directory already exists: ", dir)
  }
}

create_dir_if_missing(dir_root)
create_dir_if_missing(dir_log)
create_dir_if_missing(dir_data)
options(warn = -1)
#-------------------------------------------------------------------------------
# U.S. Occupational Mobility — Replication Files
#
# Project:     U.S. Occupational Mobility Analysis
# Repository:  https://github.com/synthetic_dynasty_analysis_replicate
#
# Script:      RF1b_generate_mother_analysis_data.R
#
# Inputs:
#   - GSS microdata (via the {gssr} package): gssr::data(gss_all)
#   - GSS mother-child occupational pairs (5-class EGP):
#       Data/robustness_check/gss_mc_occ10_5class.rds
#
# Outputs:
#   - Log file:
#       code/_LOGS/Data/robustness_check_mother_log.txt
#   - Analytical dataset:
#       - Data/robustness_check/gss_ms_occ10_5class.rds
#       - Data/robustness_check/gss_md_occ10_5class.rds
#
# Description:
#   This script constructs the analytical samples for the gender robustness
#   check on the mother's side. It separates the mother-child occupational
#   pairs (generated by RE1_generate_gender_analysis_data.R) into
#   mother-son and mother-daughter pairs, following the same procedure used
#   to separate the father-child pairs into father-son and father-daughter
#   pairs.
#
# Notes:
#   - The GSS input is accessed programmatically through {gssr}. For exact
#     replication, ensure the installed {gssr} version (and its bundled GSS
#     release) matches the version used in the analysis.
#
#-------------------------------------------------------------------------------

#-------------------------------------------------#
#  INSTALL/LOAD DEPENDENCIES AND CMED R PACKAGE   #
#-------------------------------------------------#
if(HPC){
  .libPaths(c("/home/weiqiw/R/x86_64-pc-linux-gnu-library/4.4", .libPaths()))
  library("tidyverse")
  library("readr")
  library("haven")
  library("dplyr")
}else{
  packages <-
    c(
      "tidyverse",
      "readr",
      "dplyr",
      "haven"
    )

  install_and_load <- function(pkg_list) {
    for (pkg in pkg_list) {
      if (!requireNamespace(pkg, quietly = TRUE)) {
        message("Installing missing package: ", pkg)
        install.packages(pkg, dependencies = TRUE)
      }
      library(pkg, character.only = TRUE)
    }
  }

  install_and_load(packages)
}


#-------------------------------------------------#
#     LOAD GSS DATA AND MOTHER-CHILD PAIRS
#-------------------------------------------------#

# Load GSS microdata (via the {gssr} package)
# Install from r-universe if not already available

if(HPC){
  gss_all <- read_dta(
    file.path(
      dir_root,
      "Data",
      "gss7224_r2.dta"
    )
  )

}else{
  if (!requireNamespace("gssr", quietly = TRUE)) {
    install.packages(
      "gssr",
      repos = c(
        "https://kjhealy.r-universe.dev",
        "https://cloud.r-project.org"
      )
    )
  }
  library(gssr)
  data(gss_all)
}


# Load the mother-child occupational pairs (5-class EGP):

gss_mc_occ10_5class <- readr::read_rds(
  file.path(
    dir_data,
    "gss_mc_occ10_5class.rds"
  )
)

#-------------------------------------------------#
#             ONLY KEEP MOTHER-SON PAIRS:
#-------------------------------------------------#

gss_ms_occ10_5class <-
  gss_mc_occ10_5class %>%
  left_join(
    gss_all %>%
      mutate(
        uniqid = row_number()
      ) %>%
      dplyr::select(
        uniqid,
        sex
      ),
    by = "uniqid"
  ) %>%
  filter(
    sex == 1
  )


#-------------------------------------------------#
#           ONLY KEEP MOTHER-DAUGHTER PAIRS:
#-------------------------------------------------#

gss_md_occ10_5class <-
  gss_mc_occ10_5class %>%
  left_join(
    gss_all %>%
      mutate(
        uniqid = row_number()
      ) %>%
      dplyr::select(
        uniqid,
        sex
      ),
    by = "uniqid"
  ) %>%
  filter(
    sex == 2
  )




#-----------------------------#
#  Save the Data:
#-----------------------------#

write_rds(
  gss_ms_occ10_5class,
  file.path(
    dir_data,
    "gss_ms_occ10_5class.rds")
)

write_rds(
  gss_md_occ10_5class,
  file.path(
    dir_data,
    "gss_md_occ10_5class.rds")
)


# Open log：
sink(log_path, split = TRUE)

cat("Saved processed data to: ", dir_data, "\n")
cat("Mother-son and mother-daughter occupational pairs
    for robustness check has been generated.\n")

sink()
